name: cv
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # Navigation
  auto_route: 7.8.0
  # Http
  dio: 5.3.2
  # State
  provider: 6.0.5
  # Storage
  shared_preferences: 2.1.0
  # Localization
  flutter_localizations:
    sdk: flutter
  intl: 0.18.0
  # logger
  talker_flutter: ^3.1.1
  talker_dio_logger: ^2.0.0
  talker_bloc_logger: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: 2.3.3
  flutter_lints: ^2.0.0
  auto_route_generator: 7.1.1

flutter:
  uses-material-design: true

flutter_intl:
  enabled: true