name: cv
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  # Navigation
  auto_route: 7.8.0
  # Http
  dio: 5.3.2
  retrofit: 4.0.3
  # State management
  flutter_bloc: 8.1.3
  bloc_concurrency: 0.2.2
  provider: 6.0.5
  # Class modificators
  equatable: 2.0.5
  json_annotation: 4.8.1
  # Storage
  shared_preferences: 2.1.0
  # Localization
  flutter_localizations:
    sdk: flutter
  intl: 0.18.1
  # logger
  talker_flutter: 3.1.1
  talker_dio_logger: 2.0.0
  talker_bloc_logger: 2.0.0
  # charts
  fl_chart: ^0.64.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: 2.3.3
  flutter_lints: 2.0.0
  auto_route_generator: 7.1.1
  json_serializable: 6.7.1
  retrofit_generator: 8.0.3

flutter:
  uses-material-design: true

flutter_intl:
  enabled: true
